title: Xin's Home Page
# author: GitHub User
email: xinchencs@yeah.net
description: > # this means to ignore newlines until "show_exerpts:"

show_excerpts: false # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Xin Chen
  #tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  /AzureHJ
    #linkedIn: in/thelehhman
    #rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed